models:
  - model: yunconglong/Truthful_DPO_TomGrc_FusionNet_7Bx2_MoE_13B
    parameters:
      density: 1.0
      weight: 1.0
  - model: ./13B_MATH_DPO
    parameters:
      density: 0.5
      weight: [0.33, 0.4, 0.33]
  - model: ./13B_DPO
    parameters:
      density: [0.33, 0.45, 0.66]
      weight: 0.66
merge_method: dare_ties
base_model: yunconglong/Truthful_DPO_TomGrc_FusionNet_7Bx2_MoE_13B
parameters:
  normalize: true
  int8_mask: true
dtype: bfloat16
tokenizer_source : union
